### ISSUE TITLE
Simple `auth/google` provider needed in addition to gplus

### ISSUE THREAD

**Issue by aaronrosenberg** [markbates/goth#214]
Currently `gplus` is the only Google provider available for goth.   A simple google api is also needed for applications where Google+ features or Google+ accounts may not exist.

From the Google+ SignIn docs...   (https://developers.google.com/+/web/signin/)

*"Note: If you only want to sign in your users with their Google Accounts, and do not need to use any Google+ features, integrate Google Sign-In into your app without requesting the Google+ scopes as described below."*

* https://developers.google.com/identity/sign-in/web/

**Comment by wingedrhino** [comment]
A little late to this issue, but the _gplus_ endpoint works even if you don't have a Google+ Profile.

**Comment by danielbprice** [comment]
With [Google+ going away](https://www.blog.google/technology/safety-security/project-strobe/), this seems a bit more urgent-- maybe google will keep the API endpoint around, but it seems like it will be hard for people to work out that this what they want to use with Goth.

**Comment by bentranter** [comment]
The API endpoint that Goth currently uses with the `gplus` provider is the same as Google's OAuth2 package for Go, as far as I can tell.

In [`golang.org/x/oauth2/google`](https://godoc.org/golang.org/x/oauth2/google#pkg-variables), you have the following variable containing the endpoints,

```go
var Endpoint = oauth2.Endpoint{
    AuthURL:  "https://accounts.google.com/o/oauth2/auth",
    TokenURL: "https://accounts.google.com/o/oauth2/token",
}
```

and in [Goth](https://github.com/markbates/goth/blob/master/providers/gplus/gplus.go#L20-L21) we've got,

```go
const (
	authURL         string = "https://accounts.google.com/o/oauth2/auth?access_type=offline"
	tokenURL        string = "https://accounts.google.com/o/oauth2/token"
)
```

Goth also uses [googleapis.com/oauth2/v2/userinfo](https://www.googleapis.com/oauth2/v2/userinfo) to retrieve the user object, which seems to be independent of Google+. I don't think the `gplus` provider will break when Google+ goes away.

With all that said, I think it'd be best if we duplicated the current `gplus` provider, and named it `google`, so that there isn't any confusion in the future, and so people can still use the `gplus` package as to not break backwards compatibility.

**Comment by aaronrosenberg** [comment]
Thanks Ben, that's awesome.  It may seem cosmetic - but I think a name change would do a world of good.
