### ISSUE TITLE
Not working correctly for linkedin

### ISSUE THREAD

**Issue by idealogyin** [markbates/goth#33]
While connecting with linkedin it throws back and error
`You+need+to+pass+the+"state"+parameter`
````
oauth2: cannot fetch token: 400 Bad Request
Response: {"error_description":"missing required parameters, includes an invalid parameter value, parameter more than once. : code","error":"invalid_request"}
````

**Comment by markbates** [comment]
I don't use LinkedIn, so if you open a PR with a fix I'd be happy to merge it in. Thanks.

**Comment by bentranter** [comment]
After some investigation, it looks like this bug is being caused by the redefinition of `gothic.GetState` in `examples/main.go`: https://github.com/markbates/goth/blob/master/examples/main.go#L37-L40. 

LinkedIn seems to be the only provider that makes the `state` parameter required, so omitting the `state` param breaks it. I'll send a PR to fix this at some point, but I'm going to test the other major providers manually first to make sure they all are working in the example before doing so.

**Comment by Puja-K** [comment]
I am still getting this error. Can someone please tell me how to fix it?
