### ISSUE TITLE
why break tests into separate packages?

### ISSUE THREAD

**Issue by n7fury** [markbates/goth#62]
hiya,
why are test are broken into separate packages eg.( package gothic, package gothic_test ), and then the original package (eg gothic) imported, It seems to be standard practice to put both gothic.go and gothic_test.go in the same package gothic, https://golang.org/doc/code.html#Testing. Is there any reason why the test are broken into different packages.

Thanks for your great work on this package

**Comment by markbates** [comment]
The '_test' packages are considered "magic". They let you test from the outside-in. When doing that you can only test the public API of the package. 

I like this testing style because it forces you to only use the public API therefore not letting you test private functions or use tricks to make testing easier. 

It's all about forcing you to think about your public API.
